apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: centos7-dv
  namespace: default
spec:
  source:
    http:
      url: "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2009.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: "local-path"  # 可指定你的 StorageClass，或留空使用默认

---
#apiVersion: cdi.kubevirt.io/v1beta1
#kind: DataVolume
#metadata:
#  name: dv-centos7
#  namespace: default
#spec:
#  source:
#    http:
#      url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
#  pvc:
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage: 2Gi
#    # storageClassName: <你的StorageClass名>  # 如有默认SC可省略
#
